# Mandatory settings

blog_theme: light # Or use dark
name: Here's To Life
paginate: 25
url: www.herestolifeproject.com

# Build settings
theme: jekyll-theme-merlot
plugins:
  - jekyll-feed

# Optional settings

about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
discus_identifier: # Add your Disqus identifier
ga_analytics: UA-161780209-1 # Add your GA Tracking Id
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: true # Change to false if not
scrollappear_enabled: true # Change to false to disable
tag_nav_enabled: false # Change to true if you wish to show an additional 'tag-list' navigation below the header
theme_toggle: false # Change to true if you wish to show an icon in the navigation for dynamic theme toggling
social:
  dribbble: # Add your Dribbble handle
  facebook: faisalmlalani # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: faisalmlalani # Add your GitHub handle
  linkedin: faisalmlalani # Add your LinkedIn handle
  twitter: faisalmlalani # Add your Twitter handle
  email: faisalmlalani@gmail.com # Add your Email address
  bitcoin: # Add your Bitcoin link or address
  ethereum: # Add your Ethereum link or address
  gitlab: # Add your GitLab handle
  youtube: # Add your Youtube handle
  twitch: # Add your Twitch handle
  discord: # Add you Discord server invitation ID
  tumblr: # Add your Tumblr handle
  bitbucket: # Add your Bitbucket handle
  docker: # Add your Docker Hub handle
  instagram: faisalmlalani # Add your Instagram handle
  keybase: # Add your Keybase handle
  medium: # Add your Medium handle
  spotify: # Add your Spotify handle
  stackoverflow: # Add your Stack Overflow ID number
  steam: # Add your Steam handle


# Important settings (change at own risk)

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
sass:
  load_paths:
      - _sass
      - node_modules

faisal_lalani:
  name: Faisal M. Lalani
  image: documentation/authors/lalani.png